modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/CreativeCore/issues"
logoFile="creativecore.png"
license="GNU General Public License v3.0"

[[mods]]
	modId="creativecore"
	version="2.4.0"
	displayName="CreativeCore"
	side="CLIENT"
	displayURL="https://minecraft.curseforge.com/projects/creativecore"
	authors="CreativeMD"
	acceptableRemoteVersions="*"
	description='''A simple but powerful coremod.'''
	