modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/CreativeMD/CreativeCore/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="creativecore"
    logoFile="creativecore.png"
    version="2.11.28"
    displayName="CreativeCore"
    displayURL="https://modrinth.com/mod/creativecore"
    displayTest="MATCH_VERSION"
    authors="CreativeMD"
    description='''A simple but powerful coremod.'''

[[dependencies.creativecore]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"

