modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/CreativeCore/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="creativecore"
    logoFile="creativecore.png"
    version="2.11.20"
    displayName="CreativeCore"
    displayURL="https://modrinth.com/mod/creativecore"
    authors="CreativeMD"
    description='''A simple but powerful coremod.'''

[[dependencies.creativecore]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creativecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

